### ISSUE TITLE
Support AWS::Serverless::StateMachine resources

### ISSUE THREAD

**Issue by ljacobsson** [PaulShestakov/aws-step-functions-constructor#17]
Just found this extension and so far it looks great!

However, I'm missing support for `AWS::Serverless::StateMachine`:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - "AWS::Serverless-2016-10-31"
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Definition:
        StartAt: MyState
        States:
        ...
 ```
