### ISSUE TITLE
Unexpected behaviour when using `End: true` inside a Map iterator

### ISSUE THREAD

**Issue by ljacobsson** [PaulShestakov/aws-step-functions-constructor#18]
Hi, I have the following ASL:

```
StartAt: Map
States:
  Map:
    End: true
    ItemsPath: "$.Ids"
    Iterator:
      StartAt: SyncItem
      States:
        SyncItem:
          Retry:
          - ErrorEquals:
            - States.ALL
            IntervalSeconds: 1
            BackoffRate: 2
            MaxAttempts: 3
          Catch:
          - ErrorEquals:
            - States.ALL
            Next: LogError
          End: true
          OutputPath: "$.Payload"
          Parameters:
            FunctionName.$: "$.FunctionName"
            Payload:
              ItemId.$: "$.ItemId"
          Resource: arn:aws:states:::lambda:invoke
          Type: Task
        LogError:
          Type: Pass
          End: true
    MaxConcurrency: 20
    Parameters:
      FunctionName.$: "$.FunctionName"
      ItemId.$: "$$.Map.Item.Value"
    Type: Map
```

Note that successful runs of `SyncItem` exits (End: true). Same goes for `LogError`

I'm expecting the diagram to point them to `End`, but it looks like this:
![image](https://user-images.githubusercontent.com/7579097/105518478-a2442b80-5cd8-11eb-8525-6f48c83c343c.png)
